# Mel spectrogram configuration
name: melspec
fun:
  _target_: utils.audio.melspec
  n_fft: ${general.n_fft}
  win_length: ${general.win_length}
  hop_length: ${general.audio_hop_length}
  pad: ${general.pad}
  power: ${general.power}
  n_mels: ${general.n_mels}
  sample_rate: ${general.sample_rate}
  f_min: ${general.f_min}
  f_max: ${general.f_max}
